s/rosewater/hex/g
s/flamingo/hex/g
s/pink/hex/g
s/mauvre/hex/g
s/red/hex/g
s/maroon/hex/g
s/peach/hex/g
s/yellow/hex/g
s/green/hex/g
s/teal/hex/g
s/sky/hex/g
s/sapphire/hex/g
s/blue/hex/g
s/lavender/hex/g
s/text/hex/g
s/subtext1/hex/g
s/subtext0/hex/g
s/overlay2/hex/g
s/overlay1/hex/g
s/overlay0/hex/g
s/surface2/hex/g
s/surface1/hex/g
s/surface0/hex/g
s/base/hex/g
s/mantle/hex/g
s/crust/hex/g
